on:
  push:
    branches: [main]

jobs:
  Deploy:  # Capital D to match the assignment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Build  # More accurate name for CD
        run: scripts/buildprod.sh
